import csv

with open('Rejestracje.csv', mode='w') as csvfile:
    fieldnames = ['INDEX','NUMER','PATH']
    writer = csv.DictWriter(csvfile, fieldnames = fieldnames)
    writer.writeheader()
    writer.writerow({'INDEX':'1', 'NUMER':'PO5WG20', 'PATH':'Rejestracje_OCR/png/1.png'})
    writer.writerow({'INDEX':'2', 'NUMER':'CB442EP', 'PATH':'Rejestracje_OCR/png/2.png'})
    writer.writerow({'INDEX':'3', 'NUMER':'PGN395FN', 'PATH':'Rejestracje_OCR/png/3.png'})
    writer.writerow({'INDEX':'4', 'NUMER':'PGN395FN', 'PATH':'Rejestracje_OCR/png/4.png'})
    writer.writerow({'INDEX':'5', 'NUMER':'PO1G171', 'PATH':'Rejestracje_OCR/png/5.png'})
    writer.writerow({'INDEX':'6', 'NUMER':'PO5NV18', 'PATH':'Rejestracje_OCR/png/6.png'})
    writer.writerow({'INDEX':'7', 'NUMER':'PO1G171', 'PATH':'Rejestracje_OCR/png/7.png'})
    writer.writerow({'INDEX':'8', 'NUMER':'PGN395FN', 'PATH':'Rejestracje_OCR/png/8.png'})
    writer.writerow({'INDEX':'9', 'NUMER':'PGN395FN', 'PATH':'Rejestracje_OCR/png/9.png'})
    writer.writerow({'INDEX':'10', 'NUMER':'PO1G171', 'PATH':'Rejestracje_OCR/png/10.png'})
    writer.writerow({'INDEX':'11', 'NUMER':'PO198LV', 'PATH':'Rejestracje_OCR/png/11.png'})
    writer.writerow({'INDEX':'12', 'NUMER':'PO5NV18', 'PATH':'Rejestracje_OCR/png/12.png'})
    writer.writerow({'INDEX':'13', 'NUMER':'PO5NV18', 'PATH':'Rejestracje_OCR/png/13.png'})
    writer.writerow({'INDEX':'14', 'NUMER':'PO1G171', 'PATH':'Rejestracje_OCR/png/14.png'})
    writer.writerow({'INDEX':'15', 'NUMER':'PO1G171', 'PATH':'Rejestracje_OCR/png/15.png'})
    writer.writerow({'INDEX':'16', 'NUMER':'PO198LV', 'PATH':'Rejestracje_OCR/png/16.png'})
    writer.writerow({'INDEX':'17', 'NUMER':'PO198LV', 'PATH':'Rejestracje_OCR/png/17.png'})
    writer.writerow({'INDEX':'18', 'NUMER':'PO198LV', 'PATH':'Rejestracje_OCR/png/18.png'})
    writer.writerow({'INDEX':'19', 'NUMER':'PO198LV', 'PATH':'Rejestracje_OCR/png/19.png'})
    writer.writerow({'INDEX':'20', 'NUMER':'PO3J325', 'PATH':'Rejestracje_OCR/png/20.png'})
    writer.writerow({'INDEX':'21', 'NUMER':'PO3J325', 'PATH':'Rejestracje_OCR/png/21.png'})
    writer.writerow({'INDEX':'22', 'NUMER':'PO3J325', 'PATH':'Rejestracje_OCR/png/22.png'})
    writer.writerow({'INDEX':'23', 'NUMER':'PO3J325', 'PATH':'Rejestracje_OCR/png/23.png'})
    writer.writerow({'INDEX':'24', 'NUMER':'PO216SP', 'PATH':'Rejestracje_OCR/png/24.png'})
    writer.writerow({'INDEX':'25', 'NUMER':'PO216SP', 'PATH':'Rejestracje_OCR/png/25.png'})
    writer.writerow({'INDEX':'26', 'NUMER':'PO216SP', 'PATH':'Rejestracje_OCR/png/26.png'})
    writer.writerow({'INDEX':'27', 'NUMER':'PO5WG20', 'PATH':'Rejestracje_OCR/png/27.png'})
    writer.writerow({'INDEX':'28', 'NUMER':'PSR4708A', 'PATH':'Rejestracje_OCR/png/28.png'})
    writer.writerow({'INDEX':'29', 'NUMER':'PSR4708A', 'PATH':'Rejestracje_OCR/png/29.png'})
    writer.writerow({'INDEX':'30', 'NUMER':'PSR4708A', 'PATH':'Rejestracje_OCR/png/30.png'})
    writer.writerow({'INDEX':'31', 'NUMER':'PO5WG20', 'PATH':'Rejestracje_OCR/png/31.png'})
    writer.writerow({'INDEX':'32', 'NUMER':'PO720VR', 'PATH':'Rejestracje_OCR/png/32.png'})
    writer.writerow({'INDEX':'33', 'NUMER':'PO720VR', 'PATH':'Rejestracje_OCR/png/33.png'})
    writer.writerow({'INDEX':'34', 'NUMER':'PO720VR', 'PATH':'Rejestracje_OCR/png/34.png'})
    writer.writerow({'INDEX':'35', 'NUMER':'PZ1K733', 'PATH':'Rejestracje_OCR/png/35.png'})
    writer.writerow({'INDEX':'36', 'NUMER':'PKRNW25', 'PATH':'Rejestracje_OCR/png/36.png'})
    writer.writerow({'INDEX':'37', 'NUMER':'PZ1K733', 'PATH':'Rejestracje_OCR/png/37.png'})
    writer.writerow({'INDEX':'38', 'NUMER':'PZ1K733', 'PATH':'Rejestracje_OCR/png/38.png'})
    writer.writerow({'INDEX':'39', 'NUMER':'PKRNW25', 'PATH':'Rejestracje_OCR/png/39.png'})
    writer.writerow({'INDEX':'40', 'NUMER':'PKRNW25', 'PATH':'Rejestracje_OCR/png/40.png'})
    writer.writerow({'INDEX':'41', 'NUMER':'PO6T095', 'PATH':'Rejestracje_OCR/png/41.png'})
    writer.writerow({'INDEX':'42', 'NUMER':'PGN540KR', 'PATH':'Rejestracje_OCR/png/42.png'})
    writer.writerow({'INDEX':'43', 'NUMER':'PGN540KR', 'PATH':'Rejestracje_OCR/png/43.png'})
    writer.writerow({'INDEX':'44', 'NUMER':'PO7GR66', 'PATH':'Rejestracje_OCR/png/44.png'})
    writer.writerow({'INDEX':'45', 'NUMER':'PZ2PO15', 'PATH':'Rejestracje_OCR/png/45.png'})
    writer.writerow({'INDEX':'46', 'NUMER':'PGSYT99', 'PATH':'Rejestracje_OCR/png/46.png'})
    writer.writerow({'INDEX':'47', 'NUMER':'PGSYT99', 'PATH':'Rejestracje_OCR/png/47.png'})
    writer.writerow({'INDEX':'48', 'NUMER':'PZ215YS', 'PATH':'Rejestracje_OCR/png/48.png'})
    writer.writerow({'INDEX':'49', 'NUMER':'PZ215YS', 'PATH':'Rejestracje_OCR/png/49.png'})
    writer.writerow({'INDEX':'50', 'NUMER':'CMG03U4', 'PATH':'Rejestracje_OCR/png/50.png'})
    writer.writerow({'INDEX':'51', 'NUMER':'PO1AN55', 'PATH':'Rejestracje_OCR/png/51.png'})
    

       

