import csv

with open('Rejestracje.csv', mode='w') as csvfile:
    fieldnames = ['INDEX','NUMER','PATH']
    writer = csv.DictWriter(csvfile, fieldnames = fieldnames)
    writer.writeheader()
    writer.writerow({'INDEX':'1','NUMER':'PO720VR','PATH':'Baza_final/1.png'})
    writer.writerow({'INDEX':'2','NUMER':'PZ1K733','PATH':'Baza_final/2.png'})
    writer.writerow({'INDEX':'3','NUMER':'PKRNW25','PATH':'Baza_final/3.png'})
    writer.writerow({'INDEX':'4','NUMER':'PO6T095','PATH':'Baza_final/4.png'})
    writer.writerow({'INDEX':'5','NUMER':'PGN540KR','PATH':'Baza_final/5.png'})
    writer.writerow({'INDEX':'6','NUMER':'CB442EP','PATH':'Baza_final/6.png'})
    writer.writerow({'INDEX':'7','NUMER':'PZ204VG','PATH':'Baza_final/7.png'})
    writer.writerow({'INDEX':'8','NUMER':'PO4TW31','PATH':'Baza_final/8.png'})
    writer.writerow({'INDEX':'9','NUMER':'PO894CF','PATH':'Baza_final/9.png'})
    writer.writerow({'INDEX':'10','NUMER':'PZ2P843','PATH':'Baza_final/10.png'})
    writer.writerow({'INDEX':'11','NUMER':'PGN926EW','PATH':'Baza_final/11.png'})
    writer.writerow({'INDEX':'12','NUMER':'PO188XJ','PATH':'Baza_final/12.png'})
    writer.writerow({'INDEX':'13','NUMER':'PZ494NL','PATH':'Baza_final/13.png'})
    writer.writerow({'INDEX':'14','NUMER':'PZ2V700','PATH':'Baza_final/14.png'})
    writer.writerow({'INDEX':'15','NUMER':'POB26772','PATH':'Baza_final/15.png'})
    writer.writerow({'INDEX':'16','NUMER':'PSL753CE','PATH':'Baza_final/16.png'})
    writer.writerow({'INDEX':'17','NUMER':'PNT59822','PATH':'Baza_final/17.png'})
    writer.writerow({'INDEX':'18','NUMER':'PZ9933S','PATH':'Baza_final/18.png'})
    writer.writerow({'INDEX':'19','NUMER':'PO5SA86','PATH':'Baza_final/19.png'})
    writer.writerow({'INDEX':'20','NUMER':'KK59207','PATH':'Baza_final/20.png'})
    writer.writerow({'INDEX':'21','NUMER':'WY440VG','PATH':'Baza_final/21.png'})
    writer.writerow({'INDEX':'22','NUMER':'PO894CF','PATH':'Baza_final/22.png'})
    writer.writerow({'INDEX':'23','NUMER':'PO9UH42','PATH':'Baza_final/23.png'})
    writer.writerow({'INDEX':'24','NUMER':'PZ839YT','PATH':'Baza_final/24.png'})
    writer.writerow({'INDEX':'25','NUMER':'PY45670','PATH':'Baza_final/25.png'})
    writer.writerow({'INDEX':'26','NUMER':'PZ372YA','PATH':'Baza_final/26.png'})
    writer.writerow({'INDEX':'27','NUMER':'PO8G447','PATH':'Baza_final/27.png'})
    writer.writerow({'INDEX':'28','NUMER':'PN53560','PATH':'Baza_final/28.png'})
    writer.writerow({'INDEX':'29','NUMER':'PO8PR44','PATH':'Baza_final/29.png'})
    writer.writerow({'INDEX':'30','NUMER':'PZ499EP','PATH':'Baza_final/30.png'})
    writer.writerow({'INDEX':'31','NUMER':'PO863KN','PATH':'Baza_final/31.png'})
    writer.writerow({'INDEX':'32','NUMER':'CMG05Y3','PATH':'Baza_final/32.png'})
    writer.writerow({'INDEX':'33','NUMER':'PO331PF','PATH':'Baza_final/33.png'})
    writer.writerow({'INDEX':'34','NUMER':'CGD91TU','PATH':'Baza_final/34.png'})
    writer.writerow({'INDEX':'35','NUMER':'CB288HM','PATH':'Baza_final/35.png'})
    writer.writerow({'INDEX':'36','NUMER':'PO6S547','PATH':'Baza_final/36.png'})
    writer.writerow({'INDEX':'37','NUMER':'PO313MS','PATH':'Baza_final/37.png'})
    writer.writerow({'INDEX':'38','NUMER':'PY15105','PATH':'Baza_final/38.png'})
    writer.writerow({'INDEX':'39','NUMER':'PZ2W337','PATH':'Baza_final/39.png'})
    writer.writerow({'INDEX':'40','NUMER':'PO2240K','PATH':'Baza_final/40.png'})
    writer.writerow({'INDEX':'41','NUMER':'PO9PN42','PATH':'Baza_final/41.png'})
    writer.writerow({'INDEX':'42','NUMER':'PP2014T','PATH':'Baza_final/42.png'})
    writer.writerow({'INDEX':'43','NUMER':'PZ839PP','PATH':'Baza_final/43.png'})
    writer.writerow({'INDEX':'44','NUMER':'PO3037M','PATH':'Baza_final/44.png'})
    writer.writerow({'INDEX':'45','NUMER':'PO326GU','PATH':'Baza_final/45.png'})
    writer.writerow({'INDEX':'46','NUMER':'PL7567A','PATH':'Baza_final/46.png'})
    writer.writerow({'INDEX':'47','NUMER':'PMI13258','PATH':'Baza_final/47.png'})
    writer.writerow({'INDEX':'48','NUMER':'PO249PK','PATH':'Baza_final/48.png'})
    writer.writerow({'INDEX':'49','NUMER':'PO249PK','PATH':'Baza_final/49.png'})
    writer.writerow({'INDEX':'50','NUMER':'PMI13258','PATH':'Baza_final/50.png'})
    writer.writerow({'INDEX':'51','NUMER':'PO249PK','PATH':'Baza_final/51.png'})
    writer.writerow({'INDEX':'52','NUMER':'EZG92670','PATH':'Baza_final/52.png'})
    writer.writerow({'INDEX':'53','NUMER':'PY03504','PATH':'Baza_final/53.png'})
    writer.writerow({'INDEX':'54','NUMER':'PO2T546','PATH':'Baza_final/54.png'})
    writer.writerow({'INDEX':'55','NUMER':'SL2082A','PATH':'Baza_final/55.png'})
    writer.writerow({'INDEX':'56','NUMER':'PO5T621','PATH':'Baza_final/56.png'})
    writer.writerow({'INDEX':'57','NUMER':'DLBPF97','PATH':'Baza_final/57.png'})
    writer.writerow({'INDEX':'58','NUMER':'PZ522EG','PATH':'Baza_final/58.png'})
    writer.writerow({'INDEX':'59','NUMER':'PO7RY76','PATH':'Baza_final/59.png'})
    writer.writerow({'INDEX':'60','NUMER':'PO866VJ','PATH':'Baza_final/60.png'})
    writer.writerow({'INDEX':'61','NUMER':'PO4T233','PATH':'Baza_final/61.png'})
    writer.writerow({'INDEX':'62','NUMER':'PZ201XM','PATH':'Baza_final/62.png'})
    writer.writerow({'INDEX':'63','NUMER':'DB3397A','PATH':'Baza_final/63.png'})
    writer.writerow({'INDEX':'64','NUMER':'PO4AK60','PATH':'Baza_final/64.png'})
    writer.writerow({'INDEX':'65','NUMER':'PO3MT51','PATH':'Baza_final/65.png'})
    writer.writerow({'INDEX':'66','NUMER':'PO7HK54','PATH':'Baza_final/66.png'})
    writer.writerow({'INDEX':'67','NUMER':'PY59291','PATH':'Baza_final/67.png'})
    writer.writerow({'INDEX':'68','NUMER':'ZGL78028','PATH':'Baza_final/68.png'})
    writer.writerow({'INDEX':'69','NUMER':'PO6585R','PATH':'Baza_final/69.png'})
    writer.writerow({'INDEX':'70','NUMER':'ST2652T','PATH':'Baza_final/70.png'})
    writer.writerow({'INDEX':'71','NUMER':'PO386MR','PATH':'Baza_final/71.png'})
    writer.writerow({'INDEX':'72','NUMER':'PO7SE30','PATH':'Baza_final/72.png'})
    writer.writerow({'INDEX':'73','NUMER':'PZ549EW','PATH':'Baza_final/73.png'})
    writer.writerow({'INDEX':'74','NUMER':'PO2KT44','PATH':'Baza_final/74.png'})
    writer.writerow({'INDEX':'75','NUMER':'PO2XC40','PATH':'Baza_final/75.png'})
    writer.writerow({'INDEX':'76','NUMER':'WT54581','PATH':'Baza_final/76.png'})
    writer.writerow({'INDEX':'77','NUMER':'PO3PL89','PATH':'Baza_final/77.png'})
    writer.writerow({'INDEX':'78','NUMER':'PO290TS','PATH':'Baza_final/78.png'})
    writer.writerow({'INDEX':'79','NUMER':'DJ3073C','PATH':'Baza_final/79.png'})
    writer.writerow({'INDEX':'80','NUMER':'PO2U672','PATH':'Baza_final/80.png'})
    writer.writerow({'INDEX':'81','NUMER':'PO3RE19','PATH':'Baza_final/81.png'})
    writer.writerow({'INDEX':'82','NUMER':'PO4GJ22','PATH':'Baza_final/82.png'})
    writer.writerow({'INDEX':'83','NUMER':'PO6WR37','PATH':'Baza_final/83.png'})
    writer.writerow({'INDEX':'84','NUMER':'PO7M518','PATH':'Baza_final/84.png'})
    writer.writerow({'INDEX':'85','NUMER':'PZR0893','PATH':'Baza_final/85.png'})
    writer.writerow({'INDEX':'86','NUMER':'PO4CJ32','PATH':'Baza_final/86.png'})
    writer.writerow({'INDEX':'87','NUMER':'PO4NW34','PATH':'Baza_final/87.png'})
    writer.writerow({'INDEX':'88','NUMER':'PO6KX93','PATH':'Baza_final/88.png'})
    writer.writerow({'INDEX':'89','NUMER':'PO2WC82','PATH':'Baza_final/89.png'})
    writer.writerow({'INDEX':'90','NUMER':'PO5296S','PATH':'Baza_final/90.png'})
    writer.writerow({'INDEX':'91','NUMER':'PZ681KY','PATH':'Baza_final/91.png'})
    writer.writerow({'INDEX':'92','NUMER':'PO5PM70','PATH':'Baza_final/92.png'})
    writer.writerow({'INDEX':'93','NUMER':'PO5XR93','PATH':'Baza_final/93.png'})
    writer.writerow({'INDEX':'94','NUMER':'PO301SG','PATH':'Baza_final/94.png'})
    writer.writerow({'INDEX':'95','NUMER':'PO214JN','PATH':'Baza_final/95.png'})
    writer.writerow({'INDEX':'96','NUMER':'PO229RH','PATH':'Baza_final/96.png'})
    writer.writerow({'INDEX':'97','NUMER':'PO566RP','PATH':'Baza_final/97.png'})
    writer.writerow({'INDEX':'98','NUMER':'PGN95YL','PATH':'Baza_final/98.png'})
    writer.writerow({'INDEX':'99','NUMER':'PY15364','PATH':'Baza_final/99.png'})
    writer.writerow({'INDEX':'100','NUMER':'PY09505','PATH':'Baza_final/100.png'})
    writer.writerow({'INDEX':'101','NUMER':'PZ510CA','PATH':'Baza_final/101.png'})
    writer.writerow({'INDEX':'102','NUMER':'ZPL73579','PATH':'Baza_final/102.png'})
    writer.writerow({'INDEX':'103','NUMER':'PO355PY','PATH':'Baza_final/103.png'})
    writer.writerow({'INDEX':'104','NUMER':'PO6S040','PATH':'Baza_final/104.png'})
    writer.writerow({'INDEX':'105','NUMER':'NOL8438C','PATH':'Baza_final/105.png'})
    writer.writerow({'INDEX':'106','NUMER':'PO9HC34','PATH':'Baza_final/106.png'})
    writer.writerow({'INDEX':'107','NUMER':'PO106UW','PATH':'Baza_final/107.png'})
    writer.writerow({'INDEX':'108','NUMER':'PO4JP57','PATH':'Baza_final/108.png'})
    writer.writerow({'INDEX':'109','NUMER':'PO6RS22','PATH':'Baza_final/109.png'})
    writer.writerow({'INDEX':'110','NUMER':'PO295SV','PATH':'Baza_final/110.png'})
    writer.writerow({'INDEX':'111','NUMER':'CLIUM21','PATH':'Baza_final/111.png'})
    writer.writerow({'INDEX':'112','NUMER':'PO8SX07','PATH':'Baza_final/112.png'})
    writer.writerow({'INDEX':'113','NUMER':'PO004UA','PATH':'Baza_final/113.png'})
    writer.writerow({'INDEX':'114','NUMER':'PO1PM29','PATH':'Baza_final/114.png'})
    writer.writerow({'INDEX':'115','NUMER':'PO4RW86','PATH':'Baza_final/115.png'})
    writer.writerow({'INDEX':'116','NUMER':'PO3JE76','PATH':'Baza_final/116.png'})
    writer.writerow({'INDEX':'117','NUMER':'PO7R963','PATH':'Baza_final/117.png'})
    writer.writerow({'INDEX':'118','NUMER':'PY45331','PATH':'Baza_final/118.png'})
    writer.writerow({'INDEX':'119','NUMER':'PO2HW10','PATH':'Baza_final/119.png'})
    writer.writerow({'INDEX':'120','NUMER':'PSE55882','PATH':'Baza_final/120.png'})
    writer.writerow({'INDEX':'121','NUMER':'PO528WX','PATH':'Baza_final/121.png'})
    writer.writerow({'INDEX':'122','NUMER':'PZ431SX','PATH':'Baza_final/122.png'})
    writer.writerow({'INDEX':'123','NUMER':'PO207XV','PATH':'Baza_final/123.png'})
    writer.writerow({'INDEX':'124','NUMER':'POB12291','PATH':'Baza_final/124.png'})
    writer.writerow({'INDEX':'125','NUMER':'PO2HH68','PATH':'Baza_final/125.png'})
    writer.writerow({'INDEX':'126','NUMER':'PO633KV','PATH':'Baza_final/126.png'})
    writer.writerow({'INDEX':'127','NUMER':'PO9HJ65','PATH':'Baza_final/127.png'})
    writer.writerow({'INDEX':'128','NUMER':'WN2321P','PATH':'Baza_final/128.png'})
    writer.writerow({'INDEX':'129','NUMER':'PO6GM23','PATH':'Baza_final/129.png'})
    writer.writerow({'INDEX':'130','NUMER':'PO6RL66','PATH':'Baza_final/130.png'})
    writer.writerow({'INDEX':'131','NUMER':'PO7GA70','PATH':'Baza_final/131.png'})
    writer.writerow({'INDEX':'132','NUMER':'PO6PJ89','PATH':'Baza_final/132.png'})
    writer.writerow({'INDEX':'133','NUMER':'PO9GA19','PATH':'Baza_final/133.png'})
    writer.writerow({'INDEX':'134','NUMER':'PO4SS06','PATH':'Baza_final/134.png'})
    writer.writerow({'INDEX':'135','NUMER':'PO097PE','PATH':'Baza_final/135.png'})
    writer.writerow({'INDEX':'136','NUMER':'PO4VJ10','PATH':'Baza_final/136.png'})
    writer.writerow({'INDEX':'137','NUMER':'PO4A038','PATH':'Baza_final/137.png'})
    writer.writerow({'INDEX':'138','NUMER':'PO7E077','PATH':'Baza_final/138.png'})
    writer.writerow({'INDEX':'139','NUMER':'PZ551LM','PATH':'Baza_final/139.png'})
    writer.writerow({'INDEX':'140','NUMER':'PO1330L','PATH':'Baza_final/140.png'})
    writer.writerow({'INDEX':'141','NUMER':'PO891UW','PATH':'Baza_final/141.png'})
    writer.writerow({'INDEX':'142','NUMER':'PZ1F552','PATH':'Baza_final/142.png'})
    writer.writerow({'INDEX':'143','NUMER':'PO3WY63','PATH':'Baza_final/143.png'})
    writer.writerow({'INDEX':'144','NUMER':'PGN655LF','PATH':'Baza_final/144.png'})
    writer.writerow({'INDEX':'145','NUMER':'PO299XN','PATH':'Baza_final/145.png'})
    writer.writerow({'INDEX':'146','NUMER':'PZ251YE','PATH':'Baza_final/146.png'})
    writer.writerow({'INDEX':'147','NUMER':'PO5KL59','PATH':'Baza_final/147.png'})
    writer.writerow({'INDEX':'148','NUMER':'PO7VN28','PATH':'Baza_final/148.png'})
    writer.writerow({'INDEX':'149','NUMER':'ZK0845G','PATH':'Baza_final/149.png'})
    writer.writerow({'INDEX':'150','NUMER':'PO7TF13','PATH':'Baza_final/150.png'})
    writer.writerow({'INDEX':'151','NUMER':'PO5P185','PATH':'Baza_final/151.png'})
    writer.writerow({'INDEX':'152','NUMER':'PO76902','PATH':'Baza_final/152.png'})
    writer.writerow({'INDEX':'153','NUMER':'PO9XN64','PATH':'Baza_final/153.png'})
    writer.writerow({'INDEX':'154','NUMER':'PO5SJ24','PATH':'Baza_final/154.png'})
    writer.writerow({'INDEX':'155','NUMER':'PO9MP01','PATH':'Baza_final/155.png'})
    writer.writerow({'INDEX':'156','NUMER':'PO3FA67','PATH':'Baza_final/156.png'})
    writer.writerow({'INDEX':'157','NUMER':'PO8PL36','PATH':'Baza_final/157.png'})
    writer.writerow({'INDEX':'158','NUMER':'CNA37WW','PATH':'Baza_final/158.png'})
    writer.writerow({'INDEX':'159','NUMER':'PO1SR58','PATH':'Baza_final/159.png'})
    writer.writerow({'INDEX':'160','NUMER':'PO956GP','PATH':'Baza_final/160.png'})
    writer.writerow({'INDEX':'161','NUMER':'PLE54H9','PATH':'Baza_final/161.png'})
    writer.writerow({'INDEX':'162','NUMER':'PZ1M046','PATH':'Baza_final/162.png'})
    writer.writerow({'INDEX':'163','NUMER':'PO9WW03','PATH':'Baza_final/163.png'})
    writer.writerow({'INDEX':'164','NUMER':'PZ838WM','PATH':'Baza_final/164.png'})
    writer.writerow({'INDEX':'165','NUMER':'PO9UH46','PATH':'Baza_final/165.png'})
    writer.writerow({'INDEX':'166','NUMER':'PO057XK','PATH':'Baza_final/166.png'})
    writer.writerow({'INDEX':'167','NUMER':'PO566RM','PATH':'Baza_final/167.png'})
    writer.writerow({'INDEX':'168','NUMER':'PZ221TK','PATH':'Baza_final/168.png'})
    writer.writerow({'INDEX':'169','NUMER':'PY04683','PATH':'Baza_final/169.png'})
    writer.writerow({'INDEX':'170','NUMER':'PO2UM37','PATH':'Baza_final/170.png'})
    writer.writerow({'INDEX':'171','NUMER':'PCH8VP1','PATH':'Baza_final/171.png'})
    writer.writerow({'INDEX':'172','NUMER':'PCH8VP1','PATH':'Baza_final/172.png'})
    writer.writerow({'INDEX':'173','NUMER':'PY08099','PATH':'Baza_final/173.png'})
    writer.writerow({'INDEX':'174','NUMER':'PO487RW','PATH':'Baza_final/174.png'})
    writer.writerow({'INDEX':'175','NUMER':'PZ122PE','PATH':'Baza_final/175.png'})
    writer.writerow({'INDEX':'176','NUMER':'PY27017','PATH':'Baza_final/176.png'})
    writer.writerow({'INDEX':'177','NUMER':'PO5AA31','PATH':'Baza_final/177.png'})
    writer.writerow({'INDEX':'178','NUMER':'PO1PC13','PATH':'Baza_final/178.png'})
    writer.writerow({'INDEX':'179','NUMER':'PO9UE87','PATH':'Baza_final/179.png'})
    writer.writerow({'INDEX':'180','NUMER':'PO7VH85','PATH':'Baza_final/180.png'})
    writer.writerow({'INDEX':'181','NUMER':'PO905FG','PATH':'Baza_final/181.png'})
    writer.writerow({'INDEX':'182','NUMER':'PZ1Y438','PATH':'Baza_final/182.png'})
    writer.writerow({'INDEX':'183','NUMER':'PO7K375','PATH':'Baza_final/183.png'})
    writer.writerow({'INDEX':'184','NUMER':'PO7W082','PATH':'Baza_final/184.png'})
    writer.writerow({'INDEX':'185','NUMER':'PO7K375','PATH':'Baza_final/185.png'})
    writer.writerow({'INDEX':'186','NUMER':'PY11282','PATH':'Baza_final/186.png'})
    writer.writerow({'INDEX':'187','NUMER':'PZ4E792','PATH':'Baza_final/187.png'})
    writer.writerow({'INDEX':'188','NUMER':'PO6WT91','PATH':'Baza_final/188.png'})
    writer.writerow({'INDEX':'189','NUMER':'PO9KW99','PATH':'Baza_final/189.png'})
    writer.writerow({'INDEX':'190','NUMER':'PY78786','PATH':'Baza_final/190.png'})
    writer.writerow({'INDEX':'191','NUMER':'PY30056','PATH':'Baza_final/191.png'})
    writer.writerow({'INDEX':'192','NUMER':'PSR0228C','PATH':'Baza_final/192.png'})
    writer.writerow({'INDEX':'193','NUMER':'PZ215YS','PATH':'Baza_final/193.png'})
    writer.writerow({'INDEX':'194','NUMER':'PO5JS32','PATH':'Baza_final/194.png'})
    writer.writerow({'INDEX':'195','NUMER':'PZ3J547','PATH':'Baza_final/195.png'})
    writer.writerow({'INDEX':'196','NUMER':'PO2KK47','PATH':'Baza_final/196.png'})
    writer.writerow({'INDEX':'197','NUMER':'PO1AN55','PATH':'Baza_final/197.png'})
    writer.writerow({'INDEX':'198','NUMER':'WE8N212','PATH':'Baza_final/198.png'})
    writer.writerow({'INDEX':'199','NUMER':'PO2UN73','PATH':'Baza_final/199.png'})
    writer.writerow({'INDEX':'200','NUMER':'PO6JM40','PATH':'Baza_final/200.png'})
    writer.writerow({'INDEX':'201','NUMER':'WPI5801G','PATH':'Baza_final/201.png'})
    writer.writerow({'INDEX':'202','NUMER':'PO3J325','PATH':'Baza_final/202.png'})
    writer.writerow({'INDEX':'203','NUMER':'PSR4708A','PATH':'Baza_final/203.png'})
    writer.writerow({'INDEX':'204','NUMER':'PO5WG20','PATH':'Baza_final/204.png'})
  
    

    
    
    

   
    


   

   
   




    

    
    
 

